### ISSUE TITLE
error open com.apple.mobilemail

### ISSUE THREAD

**Issue by KinG-InFeT** [emilycestmoi/phonegap-ios-social-plugin#2]
```
2013-03-18 13:43:14.727 Linkpass[1320:c07] Launch Services: Registering unknown app identifier com.apple.mobilemail failed
2013-03-18 13:43:14.727 Linkpass[1320:c07] Launch Services: Unable to find app identifier com.apple.mobilemail
```

on xCode 4.6.3 and iphone simulator 6.1

**Comment by emilycestmoi** [comment]
From what I've read, there are problems with the social framework & the simulators. Have you tried on a real device?

**Comment by mindstorm** [comment]
maybe because the simulator has no mail app? 

i'm using this plugin on devices and don't get this error message

**Comment by emilycestmoi** [comment]
Works fine on real devices. Closing.

**Comment by prasad431** [comment]
actually i tried with device . what i did in my code is i just imported the avfoundation framework and i have created the one sample extension app 

this is the code i return in the extension.mfile
//
//  ViewController.m
//  SampleExtension
//
//  Created by MVSSPRASAD on 30/06/15.
//  Copyright (c) 2015 smaat. All rights reserved.
//

#import "ViewController.h"

@interface ViewController ()

@end

@implementation ViewController
- (void)viewDidLoad {
  [super viewDidLoad];
  // Do any additional setup after loading the view, typically from a nib.
  }
- (IBAction)actionButtonPressed:(id)sender {
  UIActivityViewController *activityVC = [[UIActivityViewController alloc] initWithActivityItems:@[self.textView.text] applicationActivities:nil];
  [self presentViewController:activityVC animated:YES completion:nil];
  }
- (void)didReceiveMemoryWarning {
  [super didReceiveMemoryWarning];
  // Dispose of any resources that can be recreated.
  }

@end

this is the .hfile for the extension
//
//  ViewController.h
//  SampleExtension
//
//  Created by MVSSPRASAD on 30/06/15.
//  Copyright (c) 2015 smaat. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface ViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITextView *textView;
@end

in my original app i mean in my app view controller.h file
i written this code
//
//  ViewController.h
//  SampleExtension
//
//  Created by MVSSPRASAD on 30/06/15.
//  Copyright (c) 2015 smaat. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface ViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITextView *textView;
@end

i written this code in .m file
//
//  ViewController.m
//  SampleExtension
//
//  Created by MVSSPRASAD on 30/06/15.
//  Copyright (c) 2015 smaat. All rights reserved.
//

#import "ViewController.h"

@interface ViewController ()

@end

@implementation ViewController
- (void)viewDidLoad {
  [super viewDidLoad];
  // Do any additional setup after loading the view, typically from a nib.
  }
- (IBAction)actionButtonPressed:(id)sender {
  UIActivityViewController *activityVC = [[UIActivityViewController alloc] initWithActivityItems:@[self.textView.text] applicationActivities:nil];
  [self presentViewController:activityVC animated:YES completion:nil];
  }
- (void)didReceiveMemoryWarning {
  [super didReceiveMemoryWarning];
  // Dispose of any resources that can be recreated.
  }

@end
![screen shot 2015-06-30 at 8 10 42 pm](https://cloud.githubusercontent.com/assets/12443160/8433541/23adcc7a-1f64-11e5-9396-c0e19f811e72.png)

above one is the plist file for extension

![screen shot 2015-06-30 at 8 11 43 pm](https://cloud.githubusercontent.com/assets/12443160/8433567/44968238-1f64-11e5-86a2-3d262a1d5995.png)

in that image 
![screen shot 2015-06-30 at 8 12 51 pm](https://cloud.githubusercontent.com/assets/12443160/8433595/6c4eb228-1f64-11e5-9135-19a1ebebcc98.png)
i am created the ui in main.storyboard for main app

 this is the image for created the ui for the extension file when i run the app i am getting like this error

![screen shot 2015-06-30 at 8 15 09 pm](https://cloud.githubusercontent.com/assets/12443160/8433659/c02d8432-1f64-11e5-9429-5edc74f87c42.png)

i am getting like above error when i run in the simulator. when i run in the device also i am getting same iphone simulator screen but it is not returning any issue but i have to listen the sound text but i didn't get that what i have to do now for listen the text in text view like in sound but i am getting like above image for iphone .
